[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm[toml] >= 6"]
build-backend = "setuptools.build_meta"

[project]
name = "PTN-Utils"
description = "Common utilities for multiple PTN Bots"
authors = [
    { name = "Conshmea"},
    { name = "Axle Antilles"},
    { name = "IndorilReborn"}
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = [
    "discord-py>=2.0",
    "python-dotenv>=0.15.0",
    "loguru>=0.7.3",
]
dynamic = ["version"]

[tool.setuptools_scm]
# this is used populated when creating a git archive
# and when there is .git dir and/or there is no git installed
fallback_version = "0.0.0+unknown"

[tool.setuptools.packages.find]
where = ["."]
include = ["ptn_utils*"]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "PL",  # pylint-convention
    "I",   # isort
    "N",   # pep8-naming
    "RUF", # ruff
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "A",   # flake8-builtins
    "UP",  # pyupgrade
    "S",   # flake8-bandit
    "EXE", # flake8-executable
    "FA",  # flake8-annotation
    "ICN", # flake8-import-conventions
    "LOG", # flake8-logging
    "PIE", # flake8-pie
    "RSE", # flake8-raise
    "SIM", # flake8-simplify
    "TC",  # flake8-type-checking
    "PERF",# perflint
    "FURB",# refurb
    "RET", # flake8-return
    "ARG", # flake8-arguments
    "FIX", # flake8-fixme
    "DTZ", # flake8-datetimez
    "PTH", # flake8-use-pathlib
    "BLE", # flake8-blind-except
    "C90", # mccabe complexity
]
ignore = [
    # "E402",
    "E501",  # line too long, handled by ruff format
    "S101",  # use of assert - used intentionally for type narrowing
]

[tool.ty.environment]
python-version = "3.13"

[tool.basedpyright]
include = ["ptn_utils"]
reportAny = "information"
reportUnusedCallResult = false
reportMissingTypeStubs = false
